#!/usr/bin/env python3
"""RunForm local demo site: landing -> guest login -> upload -> TripoSR + Gemini report.

Run: ./.venv/bin/python site/server.py [port]   (binds 127.0.0.1, default 8138)
"""
import http.cookies
import http.server
import html as _html
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import threading
import time
import urllib.parse
import uuid

V3 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JOBS = os.path.join(V3, "site", "jobs")
TEMPLATE = os.path.join(V3, "site", "report_template.html")
TRIPOSR_SRC = os.path.join(V3, "tripoSR_src")
STEP1_PROMPT = open(os.path.join(V3, "step1_prompt.txt")).read()


def _read_key(name, *paths):
    for p in paths:
        try:
            for line in open(p):
                if line.startswith(name + "="):
                    return line.split("=", 1)[1].strip().strip("\"'")
        except OSError:
            pass
    return ""


GEMINI_KEY = os.environ.get("GEMINI_API_KEY") or _read_key(
    "GEMINI_API_KEY", os.path.join(V3, ".env"),
    "/Users/sameerhoda/Projects/running_analysis/v2/.env")


def _read_env_file(path):
    out = {}
    try:
        for line in open(path):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip().strip("\"'")
    except OSError:
        pass
    return out


_ENV = _read_env_file(os.path.join(V3, ".env"))
INWORLD_KEY = os.environ.get("INWORLD_API_KEY") or _ENV.get("INWORLD_API_KEY", "")
INWORLD_VOICE = os.environ.get("INWORLD_TTS_VOICE") or _ENV.get("INWORLD_TTS_VOICE", "Sarah")
INWORLD_MODEL = "inworld-tts-2"
INWORLD_VOICES = ["Nate", "Brian", "Liam", "Elliot", "Cooper", "Arthur"]
# Premium homepage model path (optional): Tripo v3 image-to-3D, generated by site/premium_model.py
TRIPO_KEY = os.environ.get("TRIPO_API_KEY") or _ENV.get("TRIPO_API_KEY", "")
TRIPO_MODEL = os.environ.get("TRIPO_MODEL") or _ENV.get("TRIPO_MODEL", "v3.1-20260211")
# tripo_cloud reads lane settings from the environment at build time; mirror
# .env values there so EC2's v3-tripo-cloud/.env (TRIPO_MODEL/TRIPO_FACE_LIMIT)
# takes effect without a separately exported environment.
for _k in ("TRIPO_API_KEY", "TRIPO_MODEL", "TRIPO_QUALITY", "TRIPO_FACE_LIMIT",
           "GEMINI_API_KEY", "INWORLD_API_KEY", "INWORLD_TTS_VOICE"):
    if _ENV.get(_k):
        os.environ.setdefault(_k, _ENV[_k])
# Google Analytics 4: set GA_MEASUREMENT_ID=G-XXXXXXXXXX (env or .env).
# Empty/invalid -> no tag emitted, pages render unchanged.
GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID") or _ENV.get("GA_MEASUREMENT_ID", "")
if not re.match(r"^G-[A-Z0-9]{4,}$", GA_MEASUREMENT_ID or ""):
    if GA_MEASUREMENT_ID:
        print("WARNING: GA_MEASUREMENT_ID looks wrong (want G-XXXXXXXXXX) — tag disabled", flush=True)
    GA_MEASUREMENT_ID = ""
GA_SNIPPET = ("<script async src='https://www.googletagmanager.com/gtag/js?id=" + GA_MEASUREMENT_ID + "'></script>"
              "<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}"
              "gtag('js',new Date());gtag('config','" + GA_MEASUREMENT_ID + "');</script>") if GA_MEASUREMENT_ID else ""
# Telegram completed-report notifications: TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID
# (env or .env). Unset -> notifications silently skipped, pipeline unaffected.
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN") or _ENV.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID") or _ENV.get("TELEGRAM_CHAT_ID", "")
PUBLIC_BASE_URL = ((os.environ.get("PUBLIC_BASE_URL") or _ENV.get("PUBLIC_BASE_URL", "")).strip().rstrip("/")
                   or "https://mynextpr.com")
MAX_UPLOAD = 8 * 1024 * 1024
JOB_RE = re.compile(r"^[a-zA-Z0-9_-]{1,40}$")

SESSIONS = set()
STATUS = {}  # job_id -> dict (mirrored to jobs/<id>/status.json)

ZONE_BANDS = {
    "head_neck":   ((0.86, 1.00), (0, 1, 0.15)),
    "shoulders":   ((0.74, 0.84), (-0.8, 0.15, 0.55)),
    "arms_elbows": ((0.58, 0.70), (-0.25, 0, 1)),
    "trunk_lean":  ((0.55, 0.72), (-1, 0.15, 0.1)),
    "knees":       ((0.22, 0.38), (-0.9, -0.1, 0.45)),
    "feet_strike": ((0.00, 0.14), (-1, -0.2, 0.3)),
    "hips_pelvis": ((0.42, 0.55), (0.2, 0, 1)),
}

CSS = ("<style>*{box-sizing:border-box}:root{--lime:#c8f04a;--bg:#0a0c11;--panel:#12161d;--panel2:#171d26;--ink:#f4f7f2;--dim:#8b938a;--faint:#5b635c;--line:#1c232d;--line2:#2a3441}"
       "html{background:radial-gradient(120% 80% at 70% -10%,#141b26 0,transparent 55%),var(--bg)}#dots-bg{position:fixed;inset:0;z-index:-1;pointer-events:none}body{background:transparent;font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;color:var(--ink);margin:0;-webkit-font-smoothing:antialiased}"
       ".wrap{max-width:1080px;margin:0 auto;padding:26px 22px 64px}"
       "h1{font-size:clamp(30px,5vw,48px);margin:0 0 12px;letter-spacing:-.03em;line-height:1.05}h1 .lime{color:var(--lime)}"
       ".sub{color:var(--dim);font-size:17px;line-height:1.55;max-width:52ch}"
       ".btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:linear-gradient(135deg,#dcff72,#a9e33c);color:#0e1206;font-weight:800;border:0;border-radius:12px;padding:15px 26px;font-size:16px;cursor:pointer;text-decoration:none;min-height:52px;box-shadow:0 14px 34px -12px rgba(200,240,74,.6);transition:transform .18s}"
       ".btn:hover{transform:translateY(-1px)}"
       ".btn.ghost{background:transparent;color:var(--ink);border:1px solid var(--line2);box-shadow:none;margin-left:10px}"
       ".quiet{display:inline-block;margin:16px 0 0;color:var(--dim);font-size:14px;min-height:44px;line-height:44px}"
       ".nav{display:flex;align-items:center;gap:14px;padding:18px 26px;position:sticky;top:0;z-index:20;background:linear-gradient(rgba(10,12,17,.9),rgba(10,12,17,.35));backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.05)}"
       ".brand{font-weight:800;letter-spacing:.18em;text-transform:uppercase;font-size:12px;color:var(--lime)}"
       ".navlink{margin-left:auto;color:var(--dim);font-size:13px;text-decoration:none}.navlink:hover{color:var(--ink)}"
       ".hero{display:grid;grid-template-columns:1fr 1fr;gap:36px;align-items:center;padding-top:26px}"
       ".upload{margin-top:22px}"
       ".drop{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;border:1.5px dashed var(--line2);border-radius:16px;padding:26px 20px;text-align:center;color:var(--dim);font-size:14px;background:#0f141b;cursor:pointer;transition:.2s;min-height:152px}"
       ".drop:hover,.drop.over{border-color:var(--lime);background:#11170f}"
       ".drop.has{border-style:solid;border-color:var(--lime)}"
       ".drop-ic{font-size:22px;color:var(--lime);line-height:1}"
       ".drop b{color:var(--ink);font-size:16px}"
       ".stage3d{position:relative;border-radius:20px;border:1px solid rgba(255,255,255,.06);background:radial-gradient(90% 70% at 50% 10%,#18202b,#0c1016 65%);overflow:hidden;aspect-ratio:1/1;box-shadow:0 24px 60px -24px rgba(0,0,0,.8)}"
       ".stage3d canvas{width:100%;height:100%;display:block;cursor:grab;touch-action:none}"
       ".stage3d canvas:active{cursor:grabbing}"
       ".badge{position:absolute;top:14px;right:14px;background:var(--lime);color:#0e1206;font-weight:800;border-radius:999px;padding:7px 13px;font-size:15px}"
       ".badge small{font-weight:400;font-size:11px;opacity:.7}"
       ".hint{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);font-size:11px;color:var(--dim);background:rgba(9,12,17,.6);border:1px solid var(--line);border-radius:999px;padding:4px 12px;white-space:nowrap}"
       ".load3d{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:13px;color:var(--dim)}"
       ".legend{display:flex;gap:14px;justify-content:center;flex-wrap:wrap;margin-top:14px;font-size:12px;color:var(--dim)}"
       ".legend span{display:inline-flex;align-items:center;gap:6px}.legend i{width:8px;height:8px;border-radius:50%;box-shadow:0 0 8px 1px currentColor}"
       ".steps{display:flex;gap:14px;margin-top:46px;flex-wrap:wrap}"
       ".step{flex:1;min-width:200px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px}"
       ".step b{color:var(--lime);font-size:13px}.step p{color:var(--dim);font-size:14px;margin:6px 0 0;line-height:1.5}"
       ".card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:26px;margin-top:24px}"
       "input[type=file]{margin:14px 0;font-size:15px}"
       ".meta{color:var(--dim);font-size:12.5px;margin-top:14px;line-height:1.6}"
       "a{color:var(--lime)}"
       "#bar{height:8px;background:#1e2630;border-radius:6px;overflow:hidden;margin-top:14px}"
       "#fill{height:100%;width:5%;background:var(--lime);transition:width .5s}"
       ".drop{position:relative}"
       ".preview{display:none;width:100%;max-height:170px;object-fit:cover;border-radius:10px;margin-bottom:8px;border:1px solid var(--line)}"
       ".drop.has .preview{display:block}"
       ".drop.has .drop-ic{display:none}"
       ".btn.ready{animation:btnGlow 1.8s ease-in-out infinite}"
       "@keyframes btnGlow{0%,100%{box-shadow:0 0 0 0 rgba(200,240,74,.5),0 14px 34px -12px rgba(200,240,74,.6)}50%{box-shadow:0 0 0 16px rgba(200,240,74,0),0 18px 44px -12px rgba(200,240,74,.95)}}"
       ".playfab{position:absolute;left:50%;bottom:16px;transform:translateX(-50%);display:inline-flex;align-items:center;gap:10px;background:var(--lime);color:#0e1206;font-weight:800;border:0;border-radius:999px;padding:13px 22px;font-size:14px;cursor:pointer;box-shadow:0 14px 40px -12px rgba(200,240,74,.7);z-index:3}"
       ".playfab svg{width:12px;height:13px;fill:currentColor}"
       ".stage3d video{width:100%;height:100%;display:block;object-fit:cover;background:#0c1016}"
       ":focus-visible{outline:3px solid var(--lime);outline-offset:2px;border-radius:8px}"
       "@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}"
       "@media(max-width:820px){.hero{grid-template-columns:1fr;gap:22px}.stage3d{aspect-ratio:4/3}.wrap{padding:16px 16px 56px}.step{min-width:100%}.btn{width:100%}.quiet{display:block;text-align:center}}"
       ".fold{position:relative;min-height:100vh;display:flex;align-items:center;overflow:hidden}.fold .glow{position:absolute;inset:0;pointer-events:none;background:radial-gradient(55% 45% at 76% 18%,rgba(200,240,74,.10),transparent 60%),radial-gradient(60% 60% at 8% 92%,rgba(79,124,255,.10),transparent 60%)}.fold-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:40px;align-items:center;width:100%}.fold h1{font-size:clamp(42px,7.5vw,92px);line-height:1.0;letter-spacing:-.04em;margin:0 0 16px}.fold .lead{color:var(--dim);font-size:18px;line-height:1.55;max-width:44ch}.cta-row{display:flex;gap:16px;align-items:center;margin-top:28px;flex-wrap:wrap}.ghostlink{color:var(--dim);font-size:14px;text-decoration:none}.ghostlink:hover{color:var(--lime)}.hero-vid{position:relative;justify-self:center;width:min(340px,70vw)}.hero-vid:before{content:'';position:absolute;inset:-16%;z-index:-1;filter:blur(8px);background:radial-gradient(closest-side,rgba(200,240,74,.18),transparent 70%)}.hero-vid video{width:100%;display:block;border-radius:28px;border:1px solid rgba(255,255,255,.09);background:#0c1016;box-shadow:0 40px 90px -30px rgba(0,0,0,.95)}.scrollcue{position:absolute;bottom:20px;left:50%;transform:translateX(-50%);font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:var(--faint)}.section2{display:grid;grid-template-columns:1fr 1fr;gap:38px;align-items:center;padding-top:72px}.showvid{position:relative;border-radius:22px;overflow:hidden;border:1px solid rgba(255,255,255,.06);background:#0c1016;aspect-ratio:1/1;box-shadow:0 30px 70px -30px rgba(0,0,0,.9)}.showvid video{width:100%;height:100%;object-fit:cover;display:block}.vidtag{position:absolute;top:14px;left:14px;background:rgba(9,12,17,.6);border:1px solid var(--line);color:var(--dim);font-size:11px;border-radius:999px;padding:5px 12px}.soundbtn{position:absolute;bottom:14px;left:50%;transform:translateX(-50%);background:var(--lime);color:#0e1206;font-weight:700;border:0;border-radius:999px;padding:10px 18px;font-size:13px;cursor:pointer;min-height:42px;box-shadow:0 12px 30px -10px rgba(200,240,74,.6)}.uploadcol h2{font-size:clamp(24px,3.4vw,38px);letter-spacing:-.03em;margin:0 0 8px}.lead2{color:var(--dim);font-size:15px;line-height:1.5;margin:0 0 18px;max-width:44ch}@media(max-width:820px){.fold{min-height:auto;padding:34px 0 54px}.fold-grid{grid-template-columns:1fr;gap:26px}.hero-vid{width:min(300px,64vw)}.section2{grid-template-columns:1fr;gap:26px;padding-top:48px}}</style>")


def set_status(jid, **kw):
    st = STATUS.get(jid, {"job": jid})
    st.update(kw)
    STATUS[jid] = st
    try:
        with open(os.path.join(JOBS, jid, "status.json"), "w") as f:
            json.dump(st, f)
    except OSError:
        pass
    return st


def load_status(jid):
    """Lazy-load status from disk if missing in memory (restart recovery)."""
    if jid in STATUS:
        return STATUS[jid]
    if not JOB_RE.match(jid or ""):
        return None
    try:
        with open(os.path.join(JOBS, jid, "status.json")) as f:
            st = json.load(f)
        STATUS[jid] = st
        return st
    except (OSError, ValueError):
        return None


def recover_statuses():
    """On startup: reload persisted statuses; fail jobs stuck mid-run."""
    try:
        names = os.listdir(JOBS)
    except OSError:
        return
    for jid in names:
        if jid == "demo" or not JOB_RE.match(jid):
            continue
        st = load_status(jid)
        if not st:
            continue
        if st.get("stage") in ("queued", "analyzing", "meshing"):
            set_status(jid, stage="failed",
                       error="server restarted mid-run, please re-upload")


LANDING_JS = (
  "(function(){"
  "var form=document.getElementById('upForm'),file=document.getElementById('file'),drop=document.getElementById('drop'),go=document.getElementById('go'),title=document.getElementById('dropTitle'),sub=document.getElementById('dropSub'),prev=document.getElementById('preview');"
  "function show(f){ if(!f) return; title.textContent=f.name; sub.textContent=(Math.round(f.size/1024))+' KB · ready to analyse'; drop.classList.add('has'); go.classList.add('ready'); try{ prev.src=URL.createObjectURL(f); }catch(x){} }"
  "file.addEventListener('change',function(){ show(file.files[0]); });"
  "['dragenter','dragover'].forEach(function(ev){ drop.addEventListener(ev,function(e){ e.preventDefault(); drop.classList.add('over'); }); });"
  "['dragleave','drop'].forEach(function(ev){ drop.addEventListener(ev,function(e){ e.preventDefault(); drop.classList.remove('over'); }); });"
  "drop.addEventListener('drop',function(e){ if(e.dataTransfer&&e.dataTransfer.files.length){ try{ file.files=e.dataTransfer.files; }catch(x){} show(e.dataTransfer.files[0]); } });"
  "form.addEventListener('submit',function(e){ if(!file.files.length){ e.preventDefault(); drop.classList.add('over'); title.textContent='Choose a photo first'; return; } go.textContent='Building your runner…'; go.style.pointerEvents='none'; go.style.opacity='.75'; });"
  "var ct=document.getElementById('ctaBtn'); if(ct) ct.addEventListener('click',function(e){ e.preventDefault(); var a=document.getElementById('analyse'); if(a) a.scrollIntoView({behavior:'smooth'}); });"
  "var sv=document.getElementById('showcaseVid'),sb=document.getElementById('soundToggle'); if(sb&&sv) sb.addEventListener('click',function(){ if(sv.muted){ sv.muted=false; sv.currentTime=0; sv.play(); sb.textContent='Mute'; } else { sv.muted=true; sb.textContent='Watch with sound'; } });"
  "})();"
)

LANDING = ("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
           "<title>RunForm — analyze your run form</title>"
           "<meta name=description content='Upload one running photo and get a 3D breakdown of your stride, zone by zone.'>" + GA_SNIPPET + CSS +
           "<script src=/assets/dots.js defer></script></head><body><canvas id=dots-bg></canvas>"
           "<div class=nav><span class=brand>RunForm</span><a class=navlink href='/report/demo'>See the sample report &rarr;</a></div>"
           "<main>"
           "<section class=fold id=top>"
           "<div class=glow></div>"
           "<div class='wrap fold-grid'>"
           "<div class=fold-copy>"
           "<h1>Analyze your <span class=lime>run form</span>.</h1>"
           "<p class=lead>One photo becomes a 3D breakdown of your stride &mdash; the flaws, the fixes, the drills. About two minutes.</p>"
           "<div class=cta-row><a href='#analyse' id=ctaBtn class=btn>Analyze my run &rarr;</a>"
           "<a class=ghostlink href='/report/demo'>or see a sample report</a></div>"
           "</div>"
           "<div class=hero-vid><video src='/assets/hero-run.mp4' poster='/assets/hero-run.jpg' autoplay muted loop playsinline preload=metadata></video></div>"
           "</div>"
           "<div class=scrollcue>scroll</div>"
           "</section>"
           "<section class='wrap section2' id=analyse>"
           "<div class=showvid>"
           "<video id=showcaseVid src='/assets/showcase.mp4' autoplay muted loop playsinline preload=metadata></video>"
           "<span class=vidtag>Sample runner &middot; score 73</span>"
           "<button id=soundToggle class=soundbtn type=button>Watch with sound</button>"
           "</div>"
           "<div class=uploadcol>"
           "<h2>Try it on your run</h2>"
           "<p class=lead2>Drop a side-profile running photo and we&rsquo;ll rebuild you in 3D and score every zone.</p>"
           "<form id=upForm method=post action=/api/jobs enctype='multipart/form-data'>"
           "<label id=drop class=drop for=file><input id=file type=file name=photo accept='image/jpeg,image/png,image/webp' hidden>"
           "<img id=preview class=preview alt='your run photo'>"
           "<span class=drop-ic>&#11014;</span><b id=dropTitle>Drop your run photo</b>"
           "<span id=dropSub>or tap to browse &middot; side-profile, mid-stride &middot; JPEG/PNG/WebP &le; 8 MB</span></label>"
           "<button id=go class=btn type=submit style='margin-top:16px;width:100%'>Analyse my run &rarr;</button>"
           "</form>"
           "<p class=meta>No account needed. The 3D mesh builds on this machine; the form audit runs through Gemini.</p>"
           "</div>"
           "</section>"
           "<section class='wrap steps'>"
           "<div class=step><b>1 &middot; Upload</b><p>One side-profile running photo. Nothing to install.</p></div>"
           "<div class=step><b>2 &middot; Analyse + build</b><p>Gemini scores your form; TripoSR rebuilds you in 3D, then we colour it by score.</p></div>"
           "<div class=step><b>3 &middot; Explore</b><p>A coach walkthrough with captions, then spin the model and tap any zone.</p></div>"
           "</section>"
           "</main>"
           "<script>" + LANDING_JS + "</script>"
           "</body></html>")

LOGIN = ("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
         "<title>RunForm — guest login</title>" + CSS + GA_SNIPPET + "<script src=/assets/dots.js defer></script></head><body><canvas id=dots-bg></canvas><div class=wrap>"
         "<h1>Log in <span class=lime>as guest.</span></h1>"
         "<p class=sub>No password, no email. One click gives you a demo session on this machine.</p>"
         "<div class=card><form method=post action=/login>"
         "<button class=btn type=submit name=guest value=1>Continue as guest →</button>"
         "</form><p class=meta>Demo only: the session lives in server memory and vanishes on restart.</p></div>"
         "</div></body></html>")

UPLOAD = ("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
          "<title>RunForm — upload</title>" + CSS + GA_SNIPPET + "<script src=/assets/dots.js defer></script></head><body><canvas id=dots-bg></canvas><div class=wrap>"
          "<h1>Upload <span class=lime>your run.</span></h1>"
          "<p class=sub>A side-profile shot, mid-stride if you have one. Processing takes about 2 minutes.</p>"
          "<div class=card><form method=post action=/api/jobs enctype=multipart/form-data>"
          "<input type=file name=photo accept='image/jpeg,image/png,image/webp' required><br>"
          "<button class=btn type=submit>Analyze my form →</button>"
          "</form><p class=meta>JPEG/PNG/WebP up to 8 MB. Your photo never leaves this machine except for the Gemini audit call.</p></div>"
          "</div></body></html>")

JOB_PAGE = ("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
            "<title>RunForm — building your runner</title>" + CSS + GA_SNIPPET +
            "<script src='https://unpkg.com/three@0.147.0/build/three.min.js'></script>"
            "<style>#loadwrap{position:relative;width:280px;height:280px;margin:10px auto}"
            "#loadwrap canvas{position:absolute;inset:0}"
            "#pct{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:44px;font-weight:800;color:var(--ink)}"
            "#pct small{font-size:15px;color:var(--dim);font-weight:400;margin-left:3px}"
            ".stages{list-style:none;margin:18px 0 0;padding:0;font-size:14px}"
            ".stages li{padding:7px 0;color:var(--dim);display:flex;gap:10px;align-items:center}"
            ".stages li.on{color:var(--ink)}.stages li.done{color:var(--lime)}"
            ".stages li .mk{width:18px;text-align:center}</style>"
            "<script src=/assets/dots.js defer></script></head><body><canvas id=dots-bg></canvas><div class=wrap style='text-align:center'>"
            "<h1>Building <span class=lime>your runner…</span></h1>"
            "<p class=sub>Gemini audits your form while TripoSR rebuilds your body in 3D.</p>"
            "<div class=card style='text-align:left'>"
            "<div id=thumbrow style='display:flex;gap:12px;align-items:center;margin-bottom:6px'>"
            "<img id=thumb alt='your upload' style='width:64px;height:64px;object-fit:cover;border-radius:10px;border:1px solid #1e2630;background:#10151c'>"
            "<div><div id=fname style='font-size:14px;font-weight:700;word-break:break-all'>preparing…</div>"
            "<div id=timer class=meta style='margin-top:2px'>elapsed 0:00</div></div></div>"
            "<div id=loadwrap><canvas id=lc width=560 height=560 style='width:280px;height:280px'></canvas>"
            "<div id=pct>0<small>%</small></div></div>"
            "<ul class=stages id=stages>"
            "<li data-s=queued><span class=mk>·</span>Queued</li>"
            "<li data-s=analyzing><span class=mk>·</span>Form audit — scoring zones</li>"
            "<li data-s=meshing><span class=mk>·</span>3D rebuild — growing the mesh</li>"
            "<li data-s=done><span class=mk>·</span>Bake — score + report ready</li></ul>"
            "<p class=meta id=detail></p><p class=meta>job <span id=jid style='font-family:monospace'></span></p>"
            "<p class=meta id=ncdn style='display:none'>3D preview offline (CDN blocked) — progress continues below.</p>"
            "<p><button class=btn ghost id=cancel style='background:transparent;color:var(--ink);border:1px solid #2e3945;margin:6px 0 0'>Cancel watch</button> "
            "<button class=btn ghost id=retry style='display:none;background:transparent;color:var(--ink);border:1px solid #2e3945;margin:6px 0 0 8px'>Retry</button></p></div>"
            "<script>var JID=__JID__;"
            "document.getElementById('jid').textContent=JID;"
            "var T={queued:4,analyzing:30,meshing:93,done:100,failed:100};"
            "var shown=0,target=4,term=false;"
            "var t0=Date.now();"
            "document.getElementById('thumb').src='/jobs/'+JID+'/input.jpg';"
            "document.getElementById('thumb').onerror=function(){this.style.display='none';};"
            "setInterval(function(){var s=Math.floor((Date.now()-t0)/1000);"
            "document.getElementById('timer').textContent='elapsed '+Math.floor(s/60)+':'+('0'+(s%60)).slice(-2);},1000);"
            "var cv=document.getElementById('lc');var has3d=(typeof THREE!=='undefined');"
            "if(!has3d){cv.style.display='none';document.getElementById('ncdn').style.display='block';}"
            "var rn=null,sc=null,ca=null,mesh=null,core=null;"
            "if(has3d){try{"
            "rn=new THREE.WebGLRenderer({canvas:cv,alpha:true,antialias:true});"
            "rn.setSize(560,560,false);"
            "sc=new THREE.Scene();"
            "ca=new THREE.PerspectiveCamera(40,1,0.1,50);ca.position.set(0,0,4.2);"
            "sc.add(new THREE.HemisphereLight(0xffffff,0x3a4350,1.2));"
            "var kl=new THREE.DirectionalLight(0xffffff,1.4);kl.position.set(2,3,2.5);sc.add(kl);"
            "mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1.25,2),"
            "new THREE.MeshStandardMaterial({color:0x4F7CFF,wireframe:true,transparent:true,opacity:0.9}));"
            "sc.add(mesh);"
            "core=new THREE.Mesh(new THREE.IcosahedronGeometry(0.5,1),"
            "new THREE.MeshBasicMaterial({color:0xc8f04a,wireframe:true,transparent:true,opacity:0.55}));"
            "sc.add(core);}catch(e){has3d=false;cv.style.display='none';document.getElementById('ncdn').style.display='block';}}"
            "function tick(){requestAnimationFrame(tick);"
            "if(Math.abs(target-shown)>0.05){shown+=(target-shown)*0.045;}"
            "else if(shown!==target){shown=target;}"
            "document.getElementById('pct').innerHTML=Math.floor(shown)+'<small>%</small>';"
            "if(!has3d||!rn)return;"
            "mesh.rotation.y+=0.008;mesh.rotation.x+=0.003;core.rotation.y-=0.012;"
            "var s=1+Math.sin(Date.now()/600)*0.03;mesh.scale.set(s,s,s);"
            "rn.render(sc,ca);}"
            "tick();"
            "function mark(stage){var L=document.querySelectorAll('#stages li');"
            "var order=['queued','analyzing','meshing','done'];var seen=true;"
            "for(var i=0;i<L.length;i++){var s=L[i].getAttribute('data-s');"
            "var mk=L[i].querySelector('.mk');"
            "if(s===stage){L[i].className='on';mk.textContent='◌';seen=false;}"
            "else if(order.indexOf(s)<order.indexOf(stage)||stage==='done'){L[i].className='done';mk.textContent='✓';}"
            "else{L[i].className='';mk.textContent='·';}}}"
            "var fails=0,cancelled=false;"
            "document.getElementById('cancel').onclick=function(){cancelled=true;"
            "document.getElementById('detail').textContent='Watch cancelled — your run continues in background. Re-open this page to keep watching.';"
            "document.getElementById('retry').style.display='inline-block';this.style.display='none';};"
            "document.getElementById('retry').onclick=function(){cancelled=false;fails=0;term=false;"
            "this.style.display='none';document.getElementById('cancel').style.display='inline-block';"
            "document.getElementById('detail').textContent='Reconnecting…';poll();};"
            "function poll(){if(term||cancelled)return;fetch('/api/jobs/'+JID).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(j){"
            "fails=0;"
            "target=T[j.stage]||4;mark(j.stage);"
            "document.getElementById('pct').innerHTML=Math.floor(shown)+'<small>%</small>';"
            "if(j.filename)document.getElementById('fname').textContent=j.filename;else document.getElementById('fname').textContent='run '+JID;"
            "if(j.detail)document.getElementById('detail').textContent=j.detail;"
            "if(j.stage==='done'){term=true;shown=100;"
            "document.getElementById('pct').innerHTML=\"100<small>%</small>\";"
            "document.getElementById('detail').textContent='Score '+j.score+' — opening your report…';"
            "setTimeout(function(){location.href='/report/'+JID;},1200);}"
            "if(j.stage==='failed'){term=true;"
            "document.getElementById('detail').textContent='Failed: '+(j.error||'unknown');"
            "document.getElementById('retry').style.display='inline-block';}"
            "else setTimeout(poll,2000);"
            "}).catch(function(){fails++;var wait=Math.min(15000,2000*Math.pow(2,fails-1));"
            "document.getElementById('detail').textContent='Reconnecting… (try '+fails+', retry in '+Math.round(wait/1000)+'s)';"
            "setTimeout(poll,wait);});}poll();</script></div></body></html>")


ROBOTS = ("User-agent: *\nAllow: /\n"
          "Sitemap: https://mynextpr.com/sitemap.xml\n")


def sitemap_xml():
    return ("<?xml version='1.0' encoding='UTF-8'?>"
            "<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>"
            "<url><loc>https://mynextpr.com/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url>"
            "<url><loc>https://mynextpr.com/report/demo</loc><changefreq>monthly</changefreq><priority>0.8</priority></url>"
            "</urlset>")


def page(body, code=200, ctype="text/html; charset=utf-8"):
    return code, ctype, body.encode()


def need_session(handler):
    jar = http.cookies.SimpleCookie(handler.headers.get("Cookie") or "")
    tok = jar.get("rf_guest")
    if tok and tok.value in SESSIONS:
        return True
    handler.redirect("/login")
    return False


def inworld_tts(text, voice, instruction=None):
    """Proxy a single Inworld TTS-2 request (key stays server-side). Returns dict."""
    import urllib.request
    payload = {
        "text": text,
        "voiceId": voice,
        "modelId": INWORLD_MODEL,
        "audioConfig": {"audioEncoding": "MP3", "speakingRate": 1},
        "deliveryMode": "CREATIVE",
        "language": "AUTO",
    }
    if instruction:
        payload["instruction"] = instruction[:400]
    req = urllib.request.Request(
        "https://api.inworld.ai/tts/v1/voice",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": "Basic " + INWORLD_KEY, "Content-Type": "application/json"},
        method="POST")
    with urllib.request.urlopen(req, timeout=45) as r:
        return json.loads(r.read().decode("utf-8"))


def gemini_audit(img_path):
    from PIL import Image
    from google import genai
    client = genai.Client(api_key=GEMINI_KEY)
    r = client.models.generate_content(
        model="gemini-3.8-flash", contents=[STEP1_PROMPT, Image.open(img_path)])
    text = r.text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0]
    return json.loads(text)


def ray_hit_all(T, o, d):
    import numpy as np
    e1 = T[:, 1] - T[:, 0]
    e2 = T[:, 2] - T[:, 0]
    p = np.cross(d, e2)
    det = (e1 * p).sum(1)
    ok = np.abs(det) > 1e-12
    inv = np.where(ok, 1.0 / np.where(ok, det, 1.0), 0.0)
    tv = o - T[:, 0]
    u = (tv * p).sum(1) * inv
    q = np.cross(tv, e1)
    vv = (q * d).sum(1) * inv
    t = (q * e2).sum(1) * inv
    good = ok & (u >= 0) & (vv >= 0) & (u + vv <= 1) & (t > 1e-9)
    return (t[good].min(), o + d * t[good].min()) if good.any() else (None, None)


def compute_anchors(mesh_path, zones):
    import trimesh
    import numpy as np
    m = trimesh.load(mesh_path, force="mesh")
    v = m.vertices
    tris = m.triangles
    out = {}
    missing = {}
    for z in zones:
        band_cfg = ZONE_BANDS.get(z)
        if not band_cfg:
            missing[z] = "no band config"
            continue
        (lo, hi), d = band_cfg
        band = None
        for pad in (0.0, 0.05, 0.10, 0.20):
            b = v[(v[:, 1] >= lo - pad) & (v[:, 1] <= hi + pad)]
            if len(b) >= 10:
                band = b
                break
        if band is None:
            missing[z] = "empty height band even after widening"
            continue
        c = band.mean(0)
        r = float(np.linalg.norm(band[:, [0, 2]] - c[[0, 2]], axis=1).max())
        dn = np.array(d, dtype=float) / np.linalg.norm(d)
        z_axis = np.array([0.0, 0.0, 1.0])
        y_axis = np.array([0.0, 1.0, 0.0])
        hit = None
        for origin, direction in (
            (c + dn * (r + 0.6), -dn),
            (c - dn * (r + 0.6), dn),
            (c + z_axis * (r + 0.6), -z_axis),
            (c + y_axis * 0.6, -y_axis),
        ):
            t, h = ray_hit_all(tris, origin, direction)
            if t is not None:
                hit = h
                break
        if hit is None:
            # Surface fallback: outermost band vertex along approach dir.
            i = int((band @ dn).argmax())
            surf = band[i] + dn * 0.010
            out[z] = [round(float(x), 4) for x in surf]
            missing[z] = "ray miss; surface fallback"
            continue
        out[z] = [round(float(x), 4) for x in hit + dn * 0.010]
    if missing:
        out["_missing"] = missing
    return out


def upright_bake(src_obj, dst_glb):
    import trimesh
    import numpy as np
    m = trimesh.load(src_obj, force="mesh")
    R = np.array([[0., -1., 0.], [1., 0., 0.], [0., 0., 1.]])
    m.apply_transform(np.vstack([np.hstack([R, [[0], [0], [0]]]), [0, 0, 0, 1]]))
    m.apply_translation([-m.vertices[:, 0].mean(), -m.vertices[:, 1].min(), -m.vertices[:, 2].mean()])
    _ = m.vertex_normals
    m.export(dst_glb)


def build_mesh_cloud(d, jid):
    """Tripo v3 cloud image-to-3D (~30 credits, textured). Returns mesh.glb path.

    Raises RuntimeError with a user-safe message on any failure (missing key,
    network/API error, empty result) — never a raw traceback or local path.
    """
    if not TRIPO_KEY:
        raise RuntimeError("3D build not configured: TRIPO_API_KEY is missing — "
                           "add it to .env and re-upload.")
    site_dir = os.path.join(V3, "site")
    if site_dir not in sys.path:
        sys.path.insert(0, site_dir)
    import tripo_cloud
    mesh_path = os.path.join(d, "mesh.glb")

    def say(s):
        set_status(jid, stage="meshing", detail="Cloud 3D: " + s)

    try:
        tripo_cloud.build_mesh(os.path.join(d, "input.jpg"), mesh_path, status_cb=say)
    except Exception as e:
        raise RuntimeError("Cloud 3D build failed: %s" % str(e)[-200:])
    if not os.path.exists(mesh_path):
        raise RuntimeError("Cloud 3D build produced no model — please re-upload.")
    return mesh_path


def build_mesh_triposr(d, jid):
    """Legacy local CPU rebuild. Returns mesh.glb path; raises RuntimeError."""
    outdir = os.path.join(d, "triposr")
    try:
        r = subprocess.run(
            [sys.executable, os.path.join(TRIPOSR_SRC, "run.py"),
             os.path.join(d, "input.jpg"), "--output-dir", outdir,
             "--device", "cpu", "--mc-resolution", "200"],
            cwd=TRIPOSR_SRC, capture_output=True, text=True, timeout=300)
    except Exception as e:
        raise RuntimeError("Local 3D rebuild failed: %s" % str(e)[-200:])
    obj = os.path.join(outdir, "0", "mesh.obj")
    if r.returncode != 0 or not os.path.exists(obj):
        raise RuntimeError("Local 3D rebuild failed: " + (r.stderr or r.stdout)[-200:])
    upright_bake(obj, os.path.join(d, "mesh.glb"))
    return os.path.join(d, "mesh.glb")


def build_mesh(d, jid):
    """Tripo cloud first, TripoSR fallback. Returns mesh.glb path.

    Raises RuntimeError with a user-safe message (re-upload guidance) — never
    a raw server path like the old tripoSR_src ENOENT.
    """
    try:
        return build_mesh_cloud(d, jid)
    except Exception as e:
        cloud_err = str(e)[-200:]
    if os.path.isdir(TRIPOSR_SRC):
        return build_mesh_triposr(d, jid)
    raise RuntimeError("Cloud 3D build failed (%s) and no local fallback is installed — "
                       "please re-upload." % cloud_err)


def telegram_notify(text):
    """Best-effort Telegram message via TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID.

    Never raises: returns True on ok, False when unconfigured or on any
    error, so the pipeline never depends on it.
    """
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return False
    try:
        import urllib.request
        body = urllib.parse.urlencode(
            {"chat_id": TELEGRAM_CHAT_ID, "text": text}).encode()
        req = urllib.request.Request(
            "https://api.telegram.org/bot%s/sendMessage" % TELEGRAM_BOT_TOKEN,
            data=body,
            headers={"Content-Type": "application/x-www-form-urlencoded"})
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode()).get("ok", False)
    except Exception:
        return False


def notify_report_done(jid, score):
    """Fire-and-forget completed-report notification (report URL + score)."""
    text = ("RunForm report ready — score %s/100\n"
            "%s/report/%s" % (score, PUBLIC_BASE_URL, jid))
    threading.Thread(target=telegram_notify, args=(text,), daemon=True).start()


def run_pipeline(jid):
    d = os.path.join(JOBS, jid)
    try:
        set_status(jid, stage="analyzing", detail="Gemini zone audit")
        analysis = gemini_audit(os.path.join(d, "input.jpg"))
        with open(os.path.join(d, "analysis.json"), "w") as f:
            json.dump(analysis, f)
        if not analysis.get("is_running"):
            set_status(jid, stage="failed", error="No runner detected in photo")
            return
        set_status(jid, stage="meshing", detail="Cloud 3D build (~1-3 min)")
        try:
            build_mesh(d, jid)
        except RuntimeError as e:
            set_status(jid, stage="failed", error=str(e)[-300:])
            return
        zones = [z["zone"] for z in analysis.get("findings", [])]
        zones += [z["zone"] for z in analysis.get("insufficient", [])
                  if z.get("zone") not in zones]
        if not zones:
            zones = list(ZONE_BANDS)
        with open(os.path.join(d, "anchors.json"), "w") as f:
            json.dump(compute_anchors(os.path.join(d, "mesh.glb"), zones), f)
        set_status(jid, stage="done", detail="report ready",
                   score=analysis.get("overall_score"))
        notify_report_done(jid, analysis.get("overall_score"))
    except Exception as e:
        set_status(jid, stage="failed", error=str(e)[-300:])


# --- backend-owned helpers (integrator wires into boot/routes; see handoff) ---

def sanitize_upload(img_bytes, max_dim=1600, quality=88):
    """PIL verify + EXIF rotate + downscale + normalize to JPEG. Returns JPEG bytes."""
    import io
    from PIL import Image, ImageOps
    Image.open(io.BytesIO(img_bytes)).verify()
    im = Image.open(io.BytesIO(img_bytes))
    im = ImageOps.exif_transpose(im).convert("RGB")
    im.thumbnail((max_dim, max_dim), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=quality)
    return buf.getvalue()


def restore_status_from_disk():
    """Reload STATUS from site/jobs/*/status.json; requeue stuck jobs."""
    import glob as _glob
    for sf in _glob.glob(os.path.join(JOBS, "*", "status.json")):
        jid = os.path.basename(os.path.dirname(sf))
        if not JOB_RE.match(jid):
            continue
        try:
            st = json.load(open(sf))
        except (OSError, ValueError):
            continue
        STATUS[jid] = st
        if st.get("stage") in ("queued", "analyzing", "meshing"):
            enqueue_pipeline(jid)


JOB_LOCK = threading.Lock()
ACTIVE_JOB = {"jid": None}
WORKER_TIMEOUT = 360  # seconds: never let one job stall the serial queue


def enqueue_pipeline(jid):
    """Serial queue: run now if idle, else park as queued; worker drains."""
    with JOB_LOCK:
        if ACTIVE_JOB["jid"] is None:
            ACTIVE_JOB["jid"] = jid
            threading.Thread(target=_pipeline_worker, args=(jid,), daemon=True).start()
        else:
            set_status(jid, stage="queued", detail="waiting for worker")


def _pipeline_worker(jid):
    try:
        t = threading.Thread(target=run_pipeline, args=(jid,), daemon=True)
        t.start()
        t.join(WORKER_TIMEOUT)
        if t.is_alive():
            set_status(jid, stage="failed", error="pipeline timed out — please re-upload")
    finally:
        with JOB_LOCK:
            ACTIVE_JOB["jid"] = None
            nxt = next((c for c, st in STATUS.items()
                        if st.get("stage") == "queued" and c != jid), None)
            if nxt:
                ACTIVE_JOB["jid"] = nxt
                threading.Thread(target=_pipeline_worker, args=(nxt,), daemon=True).start()


class H(http.server.BaseHTTPRequestHandler):
    server_version = "RunForm/0.1"

    def redirect(self, path, cookie=None):
        self.send_response(303)
        self.send_header("Location", path)
        if cookie:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()

    def send(self, code, ctype, body, cookie=None, cache=None):
        if isinstance(body, str):
            body = body.encode()
        import gzip as _gzip
        if (len(body) > 1024 and isinstance(ctype, str)
                and ctype.split(";")[0].strip() in ("text/html", "application/json", "text/plain")
                and "gzip" in (self.headers.get("Accept-Encoding") or "")):
            body = _gzip.compress(body, 6)
            gzipped = True
        else:
            gzipped = False
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "strict-origin-when-cross-origin")
        if gzipped:
            self.send_header("Content-Encoding", "gzip")
        if cache:
            self.send_header("Cache-Control", cache)
        self.send_header("Content-Length", str(len(body)))
        if cookie:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()
        self.wfile.write(body)

    def session_ok(self):
        jar = http.cookies.SimpleCookie(self.headers.get("Cookie") or "")
        tok = jar.get("rf_guest")
        return bool(tok and tok.value in SESSIONS)

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/":
            return self.send(*page(LANDING))
        if path == "/login":
            return self.send(*page(LOGIN))
        if path == "/upload":
            if not self.session_ok():
                return self.redirect("/login")
            return self.send(*page(UPLOAD))
        if path.startswith("/job/"):
            if not self.session_ok():
                return self.redirect("/login")
            jid = path[len("/job/"):]
            if not JOB_RE.match(jid) or not load_status(jid):
                return self.send(*page("unknown job", 404, "text/plain"))
            return self.send(*page(JOB_PAGE.replace("__JID__", json.dumps(jid))))
        if path.startswith("/api/jobs/"):
            rest = path[len("/api/jobs/"):]
            parts = rest.split("/")
            if len(parts) == 2 and parts[1] in ("analysis", "anchors") and JOB_RE.match(parts[0]):
                fp = os.path.join(JOBS, parts[0], parts[1] + ".json")
                try:
                    return self.send(*page(open(fp).read(), 200, "application/json"))
                except OSError:
                    return self.send(*page('{"error":"not found"}', 404, "application/json"))
            jid = parts[0]
            st = load_status(jid) if JOB_RE.match(jid) else None
            if not st:
                return self.send(*page('{"error":"unknown job"}', 404, "application/json"))
            return self.send(*page(json.dumps(st), 200, "application/json"))
        if path.startswith("/report/"):
            jid = path[len("/report/"):]
            if not JOB_RE.match(jid):
                return self.send(*page("unknown report", 404, "text/plain"))
            d = os.path.join(JOBS, jid)
            try:
                a = json.load(open(os.path.join(d, "analysis.json")))
                anchors = json.load(open(os.path.join(d, "anchors.json")))
            except OSError:
                return self.send(*page("report not ready", 404, "text/plain"))
            try:
                t = open(TEMPLATE).read()
            except OSError:
                return self.send(*page("report template missing", 500, "text/plain"))
            t = t.replace("__GA_SNIPPET__", GA_SNIPPET)
            t = t.replace("var ANALYSIS = __ANALYSIS_JSON__;", "var ANALYSIS = " + json.dumps(a) + ";")
            t = t.replace("var ANCHORS = __ANCHORS_JSON__;", "var ANCHORS = " + json.dumps(anchors) + ";")
            try:
                mesh_v = int(os.path.getmtime(os.path.join(d, "mesh.glb")))
            except OSError:
                mesh_v = 0
            t = t.replace("var MESH = __MESH_URL__;", "var MESH = " + json.dumps("/jobs/%s/mesh.glb?v=%d" % (jid, mesh_v)) + ";")
            base = "http://" + (self.headers.get("Host") or "127.0.0.1:8138")
            score = a.get("overall_score", "")
            title = "My run scored %s/100 in 3D — RunForm" % score
            desc = a.get("one_line_summary") or a.get("overall_label") or "See your running form rebuilt in 3D, zone by zone."
            img_rel = "/jobs/%s/input.jpg" % jid
            if not os.path.exists(os.path.join(d, "input.jpg")):
                img_rel = "/examples/images-3.jpeg"
            t = (t.replace("__OG_TITLE__", _html.escape(title, quote=True))
                  .replace("__OG_DESC__", _html.escape(desc, quote=True))
                  .replace("__OG_IMAGE__", _html.escape(base + img_rel, quote=True))
                  .replace("__OG_URL__", _html.escape(base + "/report/" + jid, quote=True)))
            return self.send(*page(t))
        if path.startswith("/jobs/"):
            parts = path[len("/jobs/"):].split("/")
            if len(parts) == 2 and JOB_RE.match(parts[0]) and parts[1] in ("mesh.glb", "input.jpg"):
                fp = os.path.join(JOBS, parts[0], parts[1])
                if os.path.exists(fp):
                    ct = "model/gltf-binary" if fp.endswith(".glb") else "image/jpeg"
                    body = open(fp, "rb").read()
                    self.send_response(200)
                    self.send_header("Content-Type", ct)
                    self.send_header("Content-Length", str(len(body)))
                    self.send_header("Last-Modified", self.date_time_string(os.path.getmtime(fp)))
                    self.send_header("Cache-Control", "public, max-age=86400")
                    self.end_headers()
                    self.wfile.write(body)
                    return
            return self.send(*page("not found", 404, "text/plain"))
        if path.startswith("/examples/"):
            fp = os.path.join(V3, "reference", "input", os.path.basename(path))
            if os.path.exists(fp) and os.path.isfile(fp):
                if fp.endswith((".jpg", ".jpeg")):
                    ct = "image/jpeg"
                elif fp.endswith(".png"):
                    ct = "image/png"
                elif fp.endswith(".webp"):
                    ct = "image/webp"
                elif fp.endswith(".avif"):
                    ct = "image/avif"
                else:
                    ct = "application/octet-stream"
                return self.send(200, ct, open(fp, "rb").read())
            return self.send(*page("not found", 404, "text/plain"))
        if path.startswith("/s/"):
            jid = path[len("/s/"):]
            if not JOB_RE.match(jid) or not load_status(jid):
                return self.send(*page("unknown link", 404, "text/plain"))
            click = {
                "t": time.time(),
                "ref": self.headers.get("Referer") or "",
                "ua": (self.headers.get("User-Agent") or "")[:200],
                "lang": self.headers.get("Accept-Language") or "",
            }
            try:
                with open(os.path.join(JOBS, jid, "clicks.jsonl"), "a") as f:
                    f.write(json.dumps(click) + "\n")
            except OSError:
                pass
            return self.redirect("/report/" + jid)
        if path.startswith("/api/links/"):
            jid = path[len("/api/links/"):]
            if not JOB_RE.match(jid):
                return self.send(*page('{"error":"bad link"}', 400, "application/json"))
            clicks = []
            try:
                with open(os.path.join(JOBS, jid, "clicks.jsonl")) as f:
                    clicks = [json.loads(l) for l in f if l.strip()]
            except (OSError, ValueError):
                pass
            return self.send(*page(json.dumps({
                "job": jid, "clicks": len(clicks),
                "last": clicks[-1] if clicks else None,
                "short": "/s/" + jid}), 200, "application/json"))
        if path == "/qa":
            fp = os.path.join(V3, "site", "qa", "latest", "index.html")
            if os.path.exists(fp):
                return self.send(*page(open(fp).read()))
            return self.send(*page("no QA runs yet", 404, "text/plain"))
        if path.startswith("/qa/"):
            fp = os.path.join(V3, "site", "qa", "latest", os.path.basename(path))
            if os.path.exists(fp) and os.path.isfile(fp):
                ct = "image/png" if fp.endswith(".png") else "application/json" if fp.endswith(".json") else "text/plain"
                return self.send(200, ct, open(fp, "rb").read(), cache="no-store")
            return self.send(*page("not found", 404, "text/plain"))
        if path == "/robots.txt":
            return self.send(*page(ROBOTS, 200, "text/plain; charset=utf-8"))
        if path == "/sitemap.xml":
            return self.send(*page(sitemap_xml(), 200, "application/xml; charset=utf-8"))
        if path == "/healthz":
            return self.send(*page(json.dumps({"ok": True, "jobs": len(STATUS),
                "inworld": bool(INWORLD_KEY)}), 200, "application/json"))
        if path == "/api/showcase":
            vp = os.path.join(V3, "site", "assets", "showcase.mp4")
            return self.send(*page(json.dumps({"video": os.path.exists(vp)}), 200, "application/json"))
        if path.startswith("/assets/"):
            fp = os.path.join(V3, "site", "assets", os.path.basename(path))
            if os.path.exists(fp) and os.path.isfile(fp):
                if fp.endswith(".mp4"):
                    ct = "video/mp4"
                    return self.send(200, ct, open(fp, "rb").read(), cache="public, max-age=604800")
                elif fp.endswith(".png"):
                    ct = "image/png"
                elif fp.endswith((".jpg", ".jpeg")):
                    ct = "image/jpeg"
                elif fp.endswith(".webm"):
                    ct = "video/webm"
                else:
                    ct = "application/octet-stream"
                return self.send(200, ct, open(fp, "rb").read(), cache="public, max-age=86400")
            return self.send(*page("not found", 404, "text/plain"))
        if path == "/api/demo":
            d = os.path.join(JOBS, "demo")
            try:
                a = json.load(open(os.path.join(d, "analysis.json")))
                an = json.load(open(os.path.join(d, "anchors.json")))
            except (OSError, ValueError):
                return self.send(*page('{"error":"no demo"}', 404, "application/json"))
            return self.send(*page(json.dumps({"analysis": a, "anchors": an}), 200, "application/json"))
        if path == "/api/tts/status":
            return self.send(*page(json.dumps({
                "configured": bool(INWORLD_KEY), "engine": "inworld",
                "model": INWORLD_MODEL, "voice": INWORLD_VOICE,
                "voices": INWORLD_VOICES}), 200, "application/json"))
        return self.send(*page("not found", 404, "text/plain"))

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/login":
            tok = secrets.token_hex(16)
            SESSIONS.add(tok)
            self.send_response(303)
            self.send_header("Location", "/upload")
            self.send_header("Set-Cookie", "rf_guest=%s; Path=/; HttpOnly" % tok)
            self.end_headers()
            return
        if path == "/api/jobs":
            newtok = None
            if not self.session_ok():
                newtok = secrets.token_hex(16)
                SESSIONS.add(newtok)
            cookie = ("rf_guest=%s; Path=/; HttpOnly" % newtok) if newtok else None
            try:
                length = int(self.headers.get("Content-Length", 0))
            except ValueError:
                length = 0
            if length <= 0 or length > MAX_UPLOAD + 65536:
                return self.send(*page('{"error":"empty or too large (8MB max)"}', 400, "application/json"))
            body = self.rfile.read(length)
            sep = body.find(b"\xff\xd8\xff")
            png = body.find(b"\x89PNG")
            webp = body.find(b"RIFF")
            starts = [s for s in (sep, png, webp) if s >= 0]
            if not starts:
                return self.send(*page('{"error":"no JPEG/PNG/WebP image found"}', 400, "application/json"))
            start = min(starts)
            endmark = body.rfind(b"\r\n--")
            img = body[start:endmark] if endmark > start else body[start:]
            m = re.search(rb'filename="([^"]{1,120})"', body[:max(0, start)])
            fname = os.path.basename(m.group(1).decode("utf-8", "replace")) if m else "upload"
            if len(img) > MAX_UPLOAD or len(img) < 1024:
                return self.send(*page('{"error":"bad image size"}', 400, "application/json"))
            try:
                img = sanitize_upload(img)
            except Exception:
                return self.send(*page('{"error":"invalid image (JPEG/PNG/WebP only)"}', 400, "application/json"))
            jid = uuid.uuid4().hex[:12]
            d = os.path.join(JOBS, jid)
            os.makedirs(d)
            with open(os.path.join(d, "input.jpg"), "wb") as f:
                f.write(img)
            set_status(jid, stage="queued", detail="waiting for worker",
                       filename=fname, started_at=time.time())
            enqueue_pipeline(jid)
            if "text/html" in (self.headers.get("Accept") or ""):
                return self.redirect("/job/" + jid, cookie)
            return self.send(*page(json.dumps({"job_id": jid}), 200, "application/json"), cookie=cookie)
        if path == "/api/tts":
            if not INWORLD_KEY:
                return self.send(*page('{"error":"tts not configured"}', 503, "application/json"))
            try:
                length = int(self.headers.get("Content-Length", 0))
            except ValueError:
                length = 0
            if length <= 0 or length > 20000:
                return self.send(*page('{"error":"bad request"}', 400, "application/json"))
            try:
                body = json.loads(self.rfile.read(length).decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                return self.send(*page('{"error":"bad json"}', 400, "application/json"))
            text = (body.get("text") or "").strip()
            if not text or len(text) > 2000:
                return self.send(*page('{"error":"text required (<=2000 chars)"}', 400, "application/json"))
            voice = body.get("voice") or INWORLD_VOICE
            if not re.match(r"^[A-Za-z][A-Za-z0-9 _-]{0,39}$", voice):
                return self.send(*page('{"error":"bad voice"}', 400, "application/json"))
            try:
                out = inworld_tts(text, voice, body.get("instruction"))
            except Exception as e:
                return self.send(*page(json.dumps({"error": "tts failed", "detail": str(e)[:160]}), 502, "application/json"))
            audio = out.get("audioContent")
            if not audio:
                return self.send(*page('{"error":"no audio"}', 502, "application/json"))
            return self.send(*page(json.dumps({"audioContent": audio}), 200, "application/json"))
        return self.send(*page("not found", 404, "text/plain"))

    def log_message(self, *a):
        pass


def seed_demo():
    os.makedirs(JOBS, exist_ok=True)
    restore_status_from_disk()
    d = os.path.join(JOBS, "demo")
    try:
        if os.path.exists(os.path.join(d, "mesh.glb")):
            STATUS["demo"] = json.load(open(os.path.join(d, "status.json")))
            return
        os.makedirs(d, exist_ok=True)
        shutil.copy(os.path.join(V3, "output", "step1_beach_fresh.json"), os.path.join(d, "analysis.json"))
        # anchors: prefer existing demo copy, else derive from output if present
        for cand in (os.path.join(V3, "site", "jobs", "demo", "anchors.json"),
                     os.path.join(V3, "output", "anchors.json")):
            if os.path.exists(cand):
                shutil.copy(cand, os.path.join(d, "anchors.json"))
                break
        else:
            with open(os.path.join(d, "anchors.json"), "w") as f:
                json.dump({}, f)
        shutil.copy(os.path.join(V3, "output", "triposr_beach_stage.glb"), os.path.join(d, "mesh.glb"))
        set_status("demo", stage="done", detail="sample report", score=63)
    except Exception as e:
        print("seed_demo skipped:", e, flush=True)


if __name__ == "__main__":
    seed_demo()  # includes restore_status_from_disk(): stuck jobs requeue via enqueue_pipeline
    if not os.path.exists(TEMPLATE):
        print("WARNING: report template missing: %s" % TEMPLATE, flush=True)
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8138
    srv = http.server.ThreadingHTTPServer(("127.0.0.1", port), H)
    print("RunForm demo at http://127.0.0.1:%d/" % port, flush=True)
    srv.serve_forever()

